# Production environment override
services:
  php:
    build:
      context: ./symfony
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET:-!ChangeMe!}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!changeMe}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!changeMe}
  
  nuxt:
    build:
      context: ./nuxt