# syntax = docker/dockerfile:1

ARG NODE_VERSION=22.9.0

FROM node:${NODE_VERSION}-slim as base

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY --link package.json yarn.lock .
RUN yarn install --frozen-lockfile

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "yarn", "run", "dev" ]